.PHONY: help clean upgrade requirements quality test validate

.DEFAULT_GOAL := help

PIP_COMPILE = pip-compile --upgrade

ifdef TOXENV
TOX := tox -- ## isolate each tox environment if TOXENV is defined
endif

APP_MODULE = web_app

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@awk -F ':.*?## ' '/^[a-zA-Z]/ && NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info

upgrade: ## update the requirements/*.txt files with the latest packages satisfying requirements/*.in
	# pip install -qr requirements/pip-tools.txt
	# Make sure to compile files after any other files they include!
	$(PIP_COMPILE) --allow-unsafe -o requirements/pip-tools.txt requirements/pip-tools.in
	$(PIP_COMPILE) -o requirements/base.txt requirements/base.in
	$(PIP_COMPILE) -o requirements/test.txt requirements/test.in


requirements: ## install core requirements
	pip install -r requirements/base.txt


quality: clean ## check coding style
	$(TOX) pylint ${APP_MODULE}
	$(TOX) pycodestyle ${APP_MODULE}
	$(TOX) pydocstyle ${APP_MODULE}
	$(TOX) isort --check-only --diff ${APP_MODULE}

test: clean ## run tests
	$(TOX) python manage.py check
	$(TOX) pytest

validate: quality test ## run tests and quality checks

dev.db-shell:
	docker exec -it db-1 psql

dev.python-shell:
	docker exec -it tubanco-server-1 /bin/bash -c "\
	python -i -c '\
from sqlalchemy.orm import Session; \
from web_app.database import engine; \
from web_app.models.todo import *; \
from sqlalchemy import select' \
	"
